services:
  api:
    build: ./services/api
    env_file: ./services/api/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: titanpark
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"