name: titanpark
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- Firebase & Auth Dependencies ---
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1

  # --- Other App Dependencies ---
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  firebase_auth_mocks: ^0.14.1

flutter:
  uses-material-design: true
