// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPesEtKvr5nN9rIiD5OG488ChYY8XlMvw',
    appId: '1:853567035612:android:b9962f7ee72c9a14493c19',
    messagingSenderId: '853567035612',
    projectId: 'titanpark-8f04d',
    storageBucket: 'titanpark-8f04d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1TfiKJOFGawsznDNzgUf7UUNYWsbrLks',
    appId: '1:853567035612:ios:eb3bd2dfaf392b1d493c19',
    messagingSenderId: '853567035612',
    projectId: 'titanpark-8f04d',
    storageBucket: 'titanpark-8f04d.firebasestorage.app',
    iosClientId:
        '853567035612-q439ughemeq37fra0fkklhcfqp91s7li.apps.googleusercontent.com',
    iosBundleId: 'com.example.titanpark',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4akFAbWW3cjW1MtLI2UdbMmLVMVp6hRg',
    appId: '1:853567035612:web:1560238852b370f7493c19',
    messagingSenderId: '853567035612',
    projectId: 'titanpark-8f04d',
    authDomain: 'titanpark-8f04d.firebaseapp.com',
    storageBucket: 'titanpark-8f04d.firebasestorage.app',
    measurementId: 'G-3JWTPH8V9P',
  );
}
